name: Build WebRTC and LLS-Player

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config git python cmake

      - name: Install JDK
        run: |
          wget https://repo.huaweicloud.com/java/jdk/8u202-b08/jdk-8u202-linux-x64.tar.gz
          tar -xzf jdk-8u202-linux-x64.tar.gz
          echo "export JAVA_HOME=$(pwd)/jdk1.8.0_202" >> $GITHUB_ENV
          echo "export CLASSPATH=.:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar" >> $GITHUB_ENV
          echo "export PATH=\$PATH:\$JAVA_HOME/bin" >> $GITHUB_ENV

      # - name: Install depot_tools
      #   run: |
      #     wget https://storage.googleapis.com/chrome-infra/depot_tools.zip
      #     unzip depot_tools.zip
      #     echo "export PATH=\$PATH:$(pwd)/depot_tools" >> $GITHUB_ENV
      #     source $GITHUB_ENV
      #     gclient

      - name: Download WebRTC M94 source code
        run: |
          mkdir webrtc
          cd webrtc
          fetch --nohooks webrtc_android
          cd src
          git checkout -b m94 branch-heads/4606
          git reset --hard b83487f08ff836437715b488f73416215e5570dd
          gclient sync

      - name: Download LLS-Player source code
        run: |
          git clone https://github.com/GrowthEase/LLS-Player.git
          cp -r LLS-Player/src/* webrtc/src/

      - name: Build LLS-Player
        run: |
          cd webrtc/src
          ./build_android.sh arm64 --enable-shared
